### PR TITLE
Resolve Animation experiments

### PR DESCRIPTION
**Pull request by lorenzoz23**
gotta be honest here... i didn't think this was gonna work but i think we did it.

i added form and results animations so that every time one is rendered again, the animations occur rather than just occurring upon first render and never again.

i added animations to the opening and closing of the track details modal.

i added an animation to the removal of a track and the ability to drag the track to the left to delete. the user can drag all along the x axis, but only dragging to the left will remove the track. however, the actual removal animation is the same for both clicking the remove button and dragging.

ngl, i'm not the happiest boy on earth when it comes to the actual removal animation because sometimes i feel it looks weird and others i think it's fine, but no matter how hard i tried, i couldn't get it to be a smooth, quick slide to the left. however, i think it does look absolutely good enough, just not great.

### CODE REVIEW

**Comment by katebrune** [comment]
these look so good, i love

some ideas:
- what if we slowed down the removal animation so its more visible ?
- the drag to the left to the remove is so cool, what if when they start dragging it we make the background on that left edge like red with a trash can or something so they know thats removing the track ?

really good work though, like i would totally merge this, why do u got a don't-merge-yet tag?

**Review by katebrune — APPROVED** [review]

**Review by katebrune — CHANGES_REQUESTED** [review]
i was gonna merge this but opened it up on my phone, and since the way im sharing it with people rn for their review is through text mostly(they'll view the mobile), i don't wanna have them not be able to scroll at all and have it feel like its frozen. i think if  we can disable the slide animation for small screens so that mobile can still function with scroll we can merge this

**Comment by lorenzoz23** [comment]
i tried with the trashcan and it did work but it looks really weird on mobile, like the whole item increases in size when they swipe to the left so i left it out for now but ill still keep trying to make it work

**Comment by katebrune** [comment]
for some reason, when i swipe left, it looks like it's about to delete but when i release my finger it goes back to the middle instead of deleting 

Also, could we increase the number of characters we show before we put "..."

image

**Review by katebrune — APPROVED** [review]

**Pull request merged**
