### PR TITLE
Resolve login moving animations

### PR DESCRIPTION
**Pull request by lorenzoz23**
i add some cool swirling colors in the background of the app. also added some cool delays to the new login so that they come in one by one.

i refactored the new login to use the login components and made a test for the new login description.

### CODE REVIEW

**Review by katebrune — CHANGES_REQUESTED** [review]
okay i love love love the swirling colors

i think we should have the moodqueue logo there the whole time instead of dropping it in, and then have the login button drop in where you had the moodqueue logo drop in, timing wise, other than that, looks so good!

edit: just went into the actual app, what if we just do the swirling on the login page & then on home page have the background be the normal gradient that it was before ?

**Comment by lorenzoz23** [comment]
the following is a honest and kinda unbiased, maybe slightly biased opinion:

i can barely ever tell if the background is moving.

that is all.

**Comment by katebrune** [comment]
rebase off master

````
git checkout master
git pull
git checkout login-moving-animations
git rebase master
````

you'll have conflicts in `components/animations/motion.ts` & `ui/backgrounds/Background.styles.ts`
so fix those up then do
```
git status
git add .
git status
git rebase --continue
```
instead of `git push` you'll have to do `git push -f` because a rebase changes the branch history
and this branch should be good

not sure if you've ever used rebase before so just wanted to let ya know about it. its basically another way of merging master into your branch, but instead of just merging it in with a merge commit, it rewrites your branch history to include the commits from master & then attach your current branch commits to the end, its really clean & i like using it so figured you'd be interested

**Comment by katebrune** [comment]
i still think that we don't need the moodqueue logo to drop it

**Pull request merged**
