### PR TITLE
Resolve Patch/mood 64: playlist integration

### PR DESCRIPTION
**Pull request by lorenzoz23**
okay, so i know there are a lot of files here but i just gotta say, most of them are like 1-2 line changes from a manic desire i had to fix something small and not wanting to create a whole new branch to do it.

that being said, i specifically removed the form title and and added in the queue/playlist buttons depending on type of user. i also made sure that three buttons looked half way decent on mobile which took some ugly doings but i think it paid off.

also also, you'll notice that some things look different... i'm just trying things out right now to see if anything sticks so can't wait to hear ur thoughts on it all.

### CODE REVIEW

**Review by katebrune — CHANGES_REQUESTED** [review]
image

i like that logo/user info area being smaller, what about pushing them out so they're aligned with the edges of the content section ?

also i like the changes to the queue description, instead of two lines, what if we did a single line with a divider, so this would be like "18 driving songs | based off your top tracks"

other than that i think it looks good

**Comment by lorenzoz23** [comment]
so, i had the results title like that (all in one row instead of two) but it looked weird and less grand so i switched it back to what it is now. i think this way is more powerful than just a single line of text but i'm happy to switch it back for comparison purposes. 

i've also had the title and user details pushed to the side before, but because they're both so small and they were so far apart, i found it hard to even notice them even with my peripheral vision. the way they are now demands more attention in my mind and  makes them more upfront and visible to the user. we can get jess' opinion on it when she's feeling better but i'll still throw up some side-by-side comparison picks just 'cause.

**Comment by lorenzoz23** [comment]
image

**Comment by katebrune** [comment]
i definitely like the logo/name pushed to the sides, it just looks cleaner, i feel like the other way just looks like we don't know how to align things ya know

i also like the one line for description more. i think having the two lines creates these bigger areas of unused space, and if it needs to be more "grand" we can increase the font size or something ?

**Pull request merged**
