### PR TITLE
Resolve Patch/mood 81: updating track buttons

### PR DESCRIPTION
**Pull request by lorenzoz23**
i added in two new icons so i could have more control over resizing them. the icons themselves are smaller but if you hover over them, the background button is still the same size and i can't really do anything about that.

i also got suddenly annoyed at how ugly i thought the mobile confirmation gradients were so i quickly updated those to be a bit more cool (hopefully.)

### CODE REVIEW

**Comment by katebrune** [comment]
wait what's the "mobile confirmation gradient" ? can you add a screenshot?

also, noticing when you click on the "more" button and then exit the modal, when you hover it, it doesn't give you the background color, i think we should look into either getting rid of the hover color or figuring out why it isn't showing up after its been clicked

**Comment by lorenzoz23** [comment]
image

**Comment by lorenzoz23** [comment]
the hover isn't working after you exit the modal because the button is still selected. i'm not sure what causes this but all you have to do is click somewhere else on the screen and everything will unselect and you can hover again. i'm really not sure how we could change that since there really isn't any function to call or prop to add to make that work, it may just be a bug with grommet or just normal behavior. i'll look into it further to see if i can fix it though.

**Comment by lorenzoz23** [comment]
so i tried and didn't come up with any fix for the hover thing. however, i noticed the error doesn't occur on mobile. there is a hover that is activated when you tap the more button and once you leave the modal you can still tap the same more button and get a background color to the button. since it only errors out on web and is specific to only the button you click, i really don't see it as a big deal. i also really like the hover indicators on web and think they are an important ui/ux element to have, so maybe we can just leave the hovers and just accept that if a user hovers over the button they just clicked they won't get an indicator.

anyways, i think we can still merge this in and just add the fix as a future improvement.

**Pull request merged**
