### PR TITLE
Resolve patch/MOOD-91: explicit content filter

### PR DESCRIPTION
**Pull request by lorenzoz23**
adding in a way to filter out explicit content.

at the moment, there is a switch that sets a local storage variable to persist the user's choice to allow explicit content or not. i also added in an explicit icon to tracks that are explicit.

i still need to do the actual filtering.

### CODE REVIEW

**Comment by lorenzoz23** [comment]
okay, so i added in the explicit content filtering. however, it should be expected that if a user has a larger percentage of explicit tracks in their liked and top tracks, or a good chunk of their top artist's top tracks are explicit, then they are sometimes not going to get all the tracks they asked for. 

example:
20 of my 50 top tracks are explicit. i want 40 sad from my top tracks. i only get a max of 30 because 20 of those were auto filtered out because they were explicit. 

now, there's nothing we could do to help remedy that situation; only the user can. they could recognize that maybe they have a significant chunk of explicit material and so the result of their above request should be expected. 

however, the one thing we can make sure of is that if they use the genre source, they should always get all the tracks they request. i changed the count for the recommended by seed API endpoint to be 100, but some genres (hip hop) only give a fraction of the tracks requested (seriously, i got 11 hip hop tracks when i requested 50 lol). again, this should be slightly expected for some genres like hip hop where a majority of the musical content is explicit by nature, so we can always do some sort of loop in order to get to the number of tracks the user requested. however, for some genres (like hip-hop again), this may result in an infinite loop lol.

**Comment by katebrune** [comment]
initially was like "wheres the filter? " 
image

but then found it on the user click thing. I think it should be more integrated into the form, because it's pretty hidden right now

**Comment by katebrune** [comment]
i also think it might be nice to have some kind of background color on the switch to tell when its on / off, because it's kind of hard to tell rn
image

image

**Comment by lorenzoz23** [comment]
the reason that it's in the "user/settings" area is because thats where spotify and other streaming services have their switch for turning on/off explicit content. it's not meant to be very obvious and in front of everything because most all users will not even think to turn it off or use it once but when they do they'll know that itll probably be where spotify keeps theirs. since all our users will be spotify users, they'll know that if they click on their profile image they'll be taken to a settings page where they can turn on/off the filter so it should be the same flow with our app.

**Comment by lorenzoz23** [comment]
also might change the label to reflect the value. 

something like "explicit content allowed" for on and "clean content only" for off. 

that would be in addition to the background color cause yeah i think that's a good idea.

**Comment by katebrune** [comment]
ah okay that makes sense

**Pull request merged**
